### ISSUE TITLE
Assertion error when using on own Kraken reports

### ISSUE THREAD

**Issue by Spenlow** [flashton2003/parse_kraken2_report#1]
Hi Philip, 

I tried using your script with the sample report you provided (worked fine), then tried with one of mine and received this error. I thought it might be to do with the additional taxonomic codes used in my file (G1, G2, G3... etc) but received the same error when I added these to your script. I'd be grateful if you had any ideas about what is going wrong here. I'm really keen to get this script working with my files and find an easier way of parsing these reports!

Many thanks,

Rob

Traceback (most recent call last): 
  File "/home/plzrja/Kraken2AnalysisPig/parse_kraken2_report.py", line 186, in <module>
    main(valid_taxa_levels, all_taxa_levels)
  File "/home/plzrja/Kraken2AnalysisPig/parse_kraken2_report.py", line 171, in main
    check_args(args, valid_taxa_levels)
  File "/home/plzrja/Kraken2AnalysisPig/parse_kraken2_report.py", line 158, in check_args
    check_args_inhandle(args.inhandle)
  File "/home/plzrja/Kraken2AnalysisPig/parse_kraken2_report.py", line 153, in check_args_inhandle
    assert os.path.exists(args_inhandle)
AssertionError

[C1_5M_R1.report.txt](https://github.com/flashton2003/parse_kraken2_report/files/14978032/C1_5M_R1.report.txt)

**Comment by flashton2003** [comment]
Hello Spenlow,

This error implies that the script can't find the input file you are giving it. Confirm that the the inhandle (the thing you pass to the -i option) is at exactly the path that you give to -i.

E.g. if your file is at the relative path my_data/example/kraken_report.txt then you should enter -i my_data/example/kraken_report.txt
